FROM python:3.12

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY docker/e2e-tests/requirements.in requirements.in
RUN pip install --no-cache-dir pip-tools
RUN pip-compile requirements.in && pip install -r requirements.txt
RUN pip install -r requirements.in
CMD ["tail", "-f", "/dev/null"]